version: "2"
services:
  app:
    image: frontend_image
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4040:4040"
    volumes: 
      - /app/node_modules
